### ISSUE TITLE
请问一下这么写好处在哪？ 我没感觉到 或许例子代码没真正业务的原因吗

### ISSUE THREAD

**Issue by jj89757hhb** [MrTung/MTRouter#1]

**Comment by MrTung** [comment]
确实是没有真正的业务组件在里面，可能不太好理解。
解释一下：一般我们做业务开发的时候A push到B，B push到C，都需要在控制器中互相引用对应的控制器，然后实例化，最后在用nav push或者present出去，这个可以理解吧？采用router中间件之后，利用runtime映射，在router里面都不需要引用控制器。直接将对应的controller实例化出来抛出去，自由选择入栈方式。可以有效降低各个业务组件之间的耦合，只需要引入中间件router就可以。这个思想在readme里面也有描述，你可以看一下。具体的可以点击查看原文。
