### ISSUE TITLE
如何解决传参问题

### ISSUE THREAD

**Issue by zengguorui** [MrTung/MTRouter#2]
用这种方式跳转界面，正反传值和代理方法之类的都没法用了。这方面是怎么解决的？

**Comment by MrTung** [comment]
感谢提出问题。
1：这种方案只是提供模块之间解耦思路。router里面代码只是返回了一个vc实例。跳转界面的方式其实还是你自己去做，我并没有写在router里面。同理，代理方法其实你依然可以自己去实现。
2：传值的话我在代码里写了一点注释，可能没写全，等下我更新一下。你需要在对应的vc中实现initViewControllerParam方法来接收params。这个我也一直在想，是不是可以考虑将这个功能当成参数来实现。欢迎你也提供解决方案。

希望对你有帮助。

**Comment by zengguorui** [comment]
@MrTung 
感谢解答疑惑。
我也没看仔细，你在
SuppressPerformSelectorLeakWarning( [controller performSelector:selector withObject:paramdic]);
这里已经做好了正向传值的处理。你的意思是，如果想做代理或者代码块的话也是在这里做处理的？
如果是的话，具体应该如何操作？我比较菜，没有依赖的话不懂的如何去访问界面上的设置。

**Comment by MrTung** [comment]
实现代理和block肯定不能再这里做的，只能出去做。不过这样的话，就得引用到对应的类的，没达到解耦的目的。
比如：main界面中需要push到A界面（A有一个代理），如果不需要实现A的代理的话，直接用router返回实例A，然后push就好了。如果要实现A的代理，就必须要在main中将router返回的vc转成A，那这样就必需要在A中引入A.h了  。这样肯定不合适。
不过你提的是一个问题，后续我考虑能不能实现一个通用的解决方案。

**Comment by zengguorui** [comment]
@MrTung 
我也是这个疑惑，就是不知道如何处理。期待你的后续方案。

**Comment by MrTung** [comment]
上传了一个利用block的回调方法，你可以看一下。

**Comment by zengguorui** [comment]
@MrTung 
感谢分享

**Comment by yiyuan-liaoqiang** [comment]
这样写的话，如果参数发生改变，还是得在每个调用router的地方修改参数啊？

**Comment by MrTung** [comment]
参数本身就是一个可变元素，如果参数发生改变，肯定要在调用的地方修改，这个是不管用什么方式都避免不了的。

**Comment by isdotjim** [comment]
搭个车...
想邀请你们来w3c.group创建项目对应的小组。w3c.group是类似知识星球的社群工具，但却不是知识付费性质的创作者社区，这里有相关的文章：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
